### ISSUE TITLE
DSPLのルールについて

### ISSUE THREAD

**Issue by akinobu1998** [RoboCupAtHomeJP/Rule2020#2]
https://github.com/RoboCupAtHomeJP/Rule2020/blob/master/rules/tidyup_ja.md に
> スコアは，ルールブックP.16に掲載されているスコアに0.3を乗じて，300点満点として採用する．

という記述があります。

ページ番号が間違っているので修正する必要があります。
また、スコアに0.3を乗じるという表現が正しいかどうか、検討する必要があります。
点数が300点満点になるように本大会向けの自己採点用スコアシートを作成する必要があります。

**Comment by TomohiroOno33** [comment]
もともと，他の競技と得点を合わせるために0.3を乗じていたと思います．
今大会では，TidyUpだけの実施ですので，そのままの得点で良いかと思います．

**Comment by HoriThe3rd** [comment]
@TomohiroOno33
ご意見ありがとうございます．
その通りです．
昨年の規定をそのまま踏襲したため，記載されてしまっています．
0.3をスコアに乗じる規定は撤廃し，純粋なスコアで順位付けが行われるよう図ります．

**Comment by akinobu1998** [comment]
@HoriThe3rd さん
ルールの記載修正、ありがとうございました。
Issueを閉じます。
